export const styles = {
  container: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  tabs: { display: "flex", backgroundColor: "#ffcccc" },
  tab: (tabNumber, currentActive) => ({
    flex: 1,
    padding: "10px",
    textAlign: "center",
    cursor: "pointer",
    backgroundColor: currentActive === tabNumber ? "#ff6666" : "#ffcccc",
    fontWeight: currentActive === tabNumber ? "bold" : "normal",
  }),
  innerContent: {
    marginTop: "10px",
    backgroundColor: "#ff9999",
    width: "80%",
    display: "flex",
    flexDirection: "column",
    borderRadius: "8px",
    padding: "20px",
    color: "white",
    position: "relative",
  },
  label: { fontWeight: "bold", marginBottom: "5px" },
  input: {
    flex: 1,
    padding: "8px",
    borderRadius: "5px",
    border: "none",
    marginBottom: "5px",
  },
  smallText: { fontSize: "12px", color: "#f0f0f0", marginBottom: "15px" },
  emailRow: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    gap: "10px",
    marginBottom: "15px",
  },
  verifyBox: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#cc0000",
    padding: "5px 10px",
    borderRadius: "6px",
    gap: "8px",
    whiteSpace: "nowrap",
  },
  verifyIcon: { width: "20px", height: "20px", backgroundColor: "white", borderRadius: "4px" },
  button: {
    backgroundColor: "#ff6666",
    border: "none",
    borderRadius: "6px",
    padding: "10px 20px",
    color: "white",
    fontWeight: "bold",
    cursor: "pointer",
    alignSelf: "flex-start",
    marginTop: "15px",
    marginBottom: "20px",
  },
  statsContainer: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
    gap: "10px",
    flexWrap: "wrap",
  },
  statBox: {
    flex: 1,
    minWidth: "120px",
    backgroundColor: "#ff8080",
    borderRadius: "8px",
    textAlign: "center",
    padding: "10px 0",
  },
  statTitle: { fontWeight: "bold", marginBottom: "5px" },
  statValue: { fontSize: "16px" },
  bottomButtonsContainer: {
    display: "flex",
    justifyContent: "center",
    gap: "15px",
    width: "100%",
    marginTop: "25px",
  },
  secondaryButton: {
    backgroundColor: "#ff6666",
    border: "none",
    borderRadius: "6px",
    padding: "10px 20px",
    color: "white",
    fontWeight: "bold",
    cursor: "pointer",
  },
  deleteButton: {
    backgroundColor: "#cc0000",
    border: "none",
    borderRadius: "6px",
    padding: "10px 20px",
    color: "white",
    fontWeight: "bold",
    cursor: "pointer",
  },
  backButton: {
    position: "absolute",
    backgroundColor: "#ff6666",
    border: "none",
    borderRadius: "6px",
    padding: "8px 12px",
    color: "white",
    cursor: "pointer",
  },
  securityContainer: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    marginTop: "50px",
  },
  deleteBox: {
    backgroundColor: "#ff8080",
    borderRadius: "8px",
    padding: "20px",
    width: "100%",
    textAlign: "left",
    marginTop: "50px",
  },
  deleteTitle: { fontWeight: "bold", fontSize: "18px", marginBottom: "10px" },
  deleteWarning: { fontSize: "14px", color: "#fff0f0" },
  deleteConfirmButton: {
    backgroundColor: "#cc0000",
    border: "none",
    borderRadius: "6px",
    padding: "10px 20px",
    color: "white",
    fontWeight: "bold",
    cursor: "pointer",
    alignSelf: "center",
    marginTop: "25px",
  },
  profileDisplayContainer: {
    display: "flex",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "20px",
  },
  leftForm: { flex: 2, display: "flex", flexDirection: "column" },
  rightProfile: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "#ff8080",
    borderRadius: "10px",
    padding: "20px",
  },
  profileImage: {
    width: "120px",
    height: "120px",
    backgroundColor: "#ffffff",
    borderRadius: "50%",
    marginBottom: "10px",
  },
  profileName: { fontWeight: "bold", fontSize: "16px" },
  profileUsername: { fontSize: "14px", color: "#f0f0f0" },

  // Existing modal styles
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  modalBox: {
    backgroundColor: "#fff",
    borderRadius: "10px",
    width: "400px",
    padding: "20px",
    boxShadow: "0 0 15px rgba(0,0,0,0.3)",
    display: "flex",
    flexDirection: "column",
    gap: "15px",
    position: "relative",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: { fontWeight: "bold", color: "black", fontSize: "18px" },
  modalClose: {
    background: "none",
    border: "none",
    fontSize: "20px",
    cursor: "pointer",
  },
  modalText: { fontSize: "14px", color: "#333" },
  modalDeleteButton: {
    backgroundColor: "#cc0000",
    border: "none",
    borderRadius: "6px",
    padding: "10px 15px",
    color: "white",
    fontWeight: "bold",
    cursor: "pointer",
    alignSelf: "center",
  },

  /* ===== New merged styles from InnerContainer3 ===== */
  creditContainer: {
    padding: "20px",
  },
  creditHeader: {
    fontWeight: "bold",
    fontSize: "20px",
    marginBottom: "20px",
  },
  creditRow: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    marginBottom: "20px",
  },
  creditCloseButton: {
    backgroundColor: "transparent",
    border: "1px solid #ccc",
    borderRadius: "6px",
    padding: "8px 12px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  creditInputGroup: {
    display: "flex",
    gap: "15px",
    flexGrow: 1,
  },
  creditInputBox: {
    flex: 1,
    border: "1px solid #ccc",
    color: "black",
    borderRadius: "8px",
    padding: "10px 15px",
    backgroundColor: "#f9f9f9",
  },
  addBankButton: {
    backgroundColor: "#007bff",
    color: "white",
    padding: "10px 20px",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  addAccountModal: {
    backgroundColor: "white",
    borderRadius: "10px",
    width: "450px",
    padding: "25px",
    boxShadow: "0 4px 20px rgba(0,0,0,0.2)",
  },
  addAccountHeader: {
    display: "flex",
    color: "black",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
  },
  addAccountImageButtons: {
    display: "flex",
    justifyContent: "space-around",
    marginBottom: "20px",
  },
  addAccountOption: {
    width: "120px",
    height: "80px",
    border: "1px solid #ccc",
    borderRadius: "8px",
    backgroundColor: "#f8f8f8",
    cursor: "pointer",
  },
  addAccountInputGroup: { marginBottom: "15px", color: "black",},
  addAccountInput: {
    width: "100%",
    padding: "8px",
    border: "1px solid #ccc",
    borderRadius: "6px",
  },
  addAccountBottomRow: {
    display: "flex",
    color: "black",
    alignItems: "center",
    justifyContent: "space-between",
  },
  addAccountSubmit: {
    backgroundColor: "#007bff",
    color: "white",
    padding: "10px 20px",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  deleteConfirmationModal: {
    backgroundColor: "white",
    color: "black",
    borderRadius: "10px",
    width: "350px",
    padding: "25px",
    boxShadow: "0 4px 20px rgba(0,0,0,0.2)",
  },
  deleteConfirmationHeader: {
    display: "flex",
    color: "black",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
  },
  deleteConfirmationButton: {
    backgroundColor: "#dc3545",
    color: "white",
    padding: "10px 20px",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: "bold",
  },
};
