// styles.js
export const styles = {
  /* === LeftPanel styles === */
  leftPanelContainer: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: "20px",
    maxWidth: "338px",
  },
  sectionColumn: {
    display: "flex",
    flexDirection: "column",
  },
  label: {
    fontWeight: "bold",
    fontSize: "12px",
  },
  inputTitle: {
    padding: "8px",
    borderRadius: "3px",
    border: "1px solid #D9D9D9",
    fontSize: "10px",
  },
  inputPricing: {
    padding: "8px",
    borderRadius: "3px 3px 0px 0px",
    border: "1px solid #D9D9D9",
    fontSize: "10px",
  },
  pricingOptions: {
    display: "flex",
    gap: "10px",
  },
  pricingButton: {
    padding: "2px 5px",
    border: "1px solid #d9d9d9",
    borderRadius: "2px",
    backgroundColor: "#fff",
    cursor: "pointer",
    fontSize: "10px",
  },
  flexRow: {
    display: "flex",
    gap: "20px",
  },
  selectBox: {
    padding: "8px",
    borderRadius: "0px 0px 3px 3px",
    border: "0.25px solid #D9D9D9",
    fontSize: "10px",
  },
    /* === Custom Dropdown styles === */
  dropdownContainer: {
    position: "relative",
    width: "100%",
  },
  dropdownButton: {
    padding: "8px",
    borderRadius: "0px 0px 3px 3px",
    border: "1px solid #D9D9D9",
    fontSize: "10px",
    backgroundColor: "#fff",
    cursor: "pointer",
    textAlign: "left",
  },
  dropdownMenu: {
    position: "absolute",
    top: "100%",
    left: 0,
    width: "100%",
    backgroundColor: "#fff",
    border: "1px solid #ccc",
    borderRadius: "3px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
    zIndex: 10,
  },
  dropdownItem: {
    padding: "6px 8px",
    fontSize: "10px",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  dropdownItemHover: {
    backgroundColor: "#FFDADA",
    color: "#D90000",
  },

  hiddenInput: {
    display: "none",
  },
  uploadButton: {
    padding: "2px 5px",
    borderRadius: "2px",
    color: "white",
    backgroundColor: "#FF6767",
    cursor: "pointer",
    fontSize: "9px",
  },
  dropZone: {
    marginTop: "10px",
    padding: "10px",
    borderRadius: "5px",
    minHeight: "100px",
    textAlign: "center",
    fontSize: "7px",
  },
  fileRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#f9f9f9",
    padding: "2px 5px",
    borderRadius: "0px",
  },
  removeFileButton: {
    background: "none",
    border: "none",
    color: "red",
    fontSize: "10px",
    cursor: "pointer",
  },
  textArea: {
    minHeight: "100px",
    maxWidth: "321px",
    borderRadius: "3px 3px 0px 0px",
    border: "1px solid #D9D9D9",
    padding: "8px",
    fontSize: "10px",
  },
  actionButtons: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "20px",
  },
  saveButton: {
    backgroundColor: "#FF6767",
    color: "white",
    padding: "10px 15px",
    borderRadius: "3px",
    border: "none",
    cursor: "pointer",
  },
  deleteButton: {
    backgroundColor: "#FF6767",
    color: "white",
    padding: "10px 15px",
    borderRadius: "3px",
    border: "none",
    cursor: "pointer",
  },

  /* === EngineTypeDropUp styles === */
  dropUpContainer: {
    display: "flex",
    justifyContent: "center",
  },
  dropUpWrapper: {
    position: "relative",
  },
  dropUpButton: {
    padding: "2px",
    border: "1px solid #D9D9D9",
    borderRadius: "0px 0px 3px 3px",
    backgroundColor: "#fff",
    cursor: "pointer",
    width: "169px",
  },
  dropUpMenu: {
    position: "absolute",
    bottom: "26px",
    left: 0,
    backgroundColor: "#fff",
    border: "1px solid #ccc",
    borderRadius: "1px",
    width: "168px",
    boxShadow: "0 2px 5px rgba(0,0,0,0.1)",
    zIndex: 1,
  },
  dropUpItem: {
    padding: "2px 12px",
    cursor: "pointer",
    transition: "all 0.2s ease",
    fontSize: "9px",
  },



  /* === RightPanel styles === */
  rightPanelContainer: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  
  },
  coverContainer: {
    position: "relative",
    width: "300px",
    height: "150px",
    border: "2px dashed #ccc",
    borderRadius: "8px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    margin: "0 auto",
  },
  coverImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  coverUploadLabel: {
    position: "absolute",
    bottom: "2px",
    left: "50%",
    transform: "translateX(-50%)",
    padding: "2px 5px",
    backgroundColor: "#000",
    color: "#fff",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "10px",
  },
  screenshotButton: {
    padding: "2px 8px",
    backgroundColor: "#FF6767",
    color: "#fff",
    borderRadius: "3px",
    cursor: "pointer",
    display: "inline-block",
    fontSize: "10px",
  },
  screenshotContainer: {
    marginTop: "10px",
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    width: "89%",
    minHeight: "100px",
    border: "2px dashed #ccc",
    borderRadius: "5px",
    padding: "10px",
  },
  screenshotImage: {
    width: "70px",
    height: "70px",
    objectFit: "cover",
    cursor: "pointer",
    borderRadius: "3px",
  },

  /* === ItemWithStats styles === */
  statBox: {
    width: "60px",
    height: "50px",
    color: "black",
    borderRadius: "3.5px",
    border: "1px solid #d9d9d9",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    fontWeight: "bold",
    fontSize: "0.6rem",
  },
  statValue: {
    fontSize: "1.2rem",
  },
  itemCard: {
    display: "flex",
    backgroundColor: "#fff",
    borderRadius: "3.5px",
    border: "1px solid #d9d9d9",
    marginLeft: "25px",
    padding: "10px",
    width: "380px",
    gap: "10px",
  },
  itemImage: {
    width: "80px",
    height: "80px",
    borderRadius: "8px",
    objectFit: "cover",
  },
  itemRight: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    justifyContent: "space-between",
  },
  itemTopRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  itemTitle: {
    fontWeight: "bold",
    fontSize: "1rem",
  },
  itemDateBlock: {
    textAlign: "center",
  },
  boldText: {
    fontWeight: "bold",
  },
  itemBottomRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: "10px",
  },
  ratingGroup: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
  },
  editButton: {
    padding: "3px 6px",
    borderRadius: "5px",
    border: "1px solid #D9D9D9",
    backgroundColor: "#fff",
    cursor: "pointer",
  },
  publishedTag: {
    backgroundColor: "#eee",
    padding: "3px 6px",
    borderRadius: "5px",
  },
  itemWithStatsContainer: {
    display: "flex",
    gap: "10px",
  },
  statsGroup: {
    display: "flex",
    gap: "2px",
  },
  currencyInputContainer: {
    position: "relative",
    width: "100%",
    
  },
  pesoSymbol: {
    position: "absolute",
    left: "10px",
    top: "50%",
    transform: "translateY(-50%)",
    color: "#555",
    fontWeight: "bold",
  },
  disabledInput: {
    backgroundColor: "#f3f3f3",
    color: "#777",
    cursor: "not-allowed",
  },
  activePricingButton: {
    backgroundColor: "#FFDADA",
    color: "#D90000",
    border: "0.25px solid #D90000",
  },

};
